image: rocker/verse

pages:
  stage: deploy
  script:
  - Rscript -e "remotes::install_github('tidyverse/tidyr')"
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook', output_dir = 'public')"
  artifacts:
    paths:
    - public
  only:
  - master